name: Python Script Workflow

on: [push]

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'
    - name: Install dependencies
      run: pip install -r requirements.txt
    - name: Run Python script
      env:
        TENANT_ID : ${{ secrets.TENANT_ID }}
        CLIENT_ID : ${{ secrets.CLIENT_ID }}
        CLIENT_SECRET : ${{ secrets.CLIENT_SECRET }}
        BASE_URL : ${{ secrets.BASE_URL }}
        CLIENT_NAME : ${{ secrets.CLIENT_NAME }}
        PROJECT_NAME : ${{ secrets.PROJECT_NAME }}
      run: python deploy.py